sudo: false
language: d
d:
  - dmd
  - ldc
os:
  - linux
install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.3.1/doveralls_linux_travis"
  - chmod +x doveralls
script:
  - dub build
  - dscanner --styleCheck source
  - dscanner --syntaxCheck source
  - dub run dich:tests
  - ./doveralls
