sudo: false
language: d
d:
  - dmd
  - ldc
os:
  - linux
jobs:
  include:
    - stage: build
      script: dub build
    - stage: test
      script: dscanner --styleCheck source
      script: dscanner --syntaxCheck source
      script: dub run dich:tests
